[package]
name = "xvi"
version = "1.2.0"
authors = ["Artem Senichev <artemsen@gmail.com>"]
edition = "2018"
homepage = "https://github.com/artemsen/xvi"

[dependencies]
ncurses = { version = "5.101.0", features = ["wide", "panel"] }
unicode-segmentation = "1.8.0"
