.TH xvi 1 "November 2021" "xvi" "XVI editor manual"
.SH NAME
xvi \- hexadecimal editor
.SH SYNOPSIS
xvi [\fIOPTIONS\fR...] \fIFILE...\fR
.SH DESCRIPTION
\fBxvi\fR is the hex editor with ncurses based user interface.
.
.SH OPTIONS
.PP
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message.
.IP "\fB\-v\fR, \fB\-\-version\fR"
Display version information.
.IP "\fB\-o\fR, \fB\-\-offset\fR \fIADDRESS\fR"
Set the initial position of the cursor.
.
.SH KEYBINDINGS
.SS Common
.IP "\fBArrows\fR and vim-like moving keys (\fBh\fR,\fBj\fR,\fBk\fR,\fBl\fR)"
Move cursor.
.IP "\fBShift+Up\fR, \fBShift+Down\fR"
Scroll 1 line up/down.
.IP "\fBShift+Left\fR, \fBShift+Right\fR"
Jump to next/previous 4-bytes aligned word.
.IP "\fBAlt+Left\fR, \fBAlt+Up\fR"
Jump to the previous closest changed byte.
.IP "\fBAlt+Right\fR, \fBAlt+Down\fR"
Jump to the next closest changed byte.
.IP "\fBTab\fR, \fBCtrl+Right\fR"
Set focus to the next field (HEX/ASCII).
.IP "\fBShift-Tab\fR, \fBCtrl+Left\fR"
Set focus to the previous field (HEX/ASCII).
.IP "\fBCtrl+Up\fR"
Set focus to the previous document.
.IP "\fBCtrl+Down\fR"
Set focus to the next document.
.IP "\fBShift+Up\fR, \fBShift+Down\fR"
Scroll 1 line up/down.
.IP "\fBPgUp\fR, \fBPgDown\fR"
Scroll 1 page up/down.
.IP "\fBHome\fR, \fBEnd\fR"
Move cursor to the start/end of the current line.
.IP "\fBCtrl+Home\fR, \fBCtrl+End\fR"
Move cursor to the start/end of the current file.
.IP "\fBCtrl+z\fR"
Undo last change.
.IP "\fBCtrl+r\fR, \fBCtrl+y\fR"
Redo last change.
.SS HEX field focused
.IP "\fBu\fR"
Undo last change.
.IP "\fBg\fR, \fBG\fR"
Move cursor to the start/end of the current file.
.IP "\fB:\fP"
Goto.
.IP "\fB/\fP"
Find.
.IP "\fBn\fP"
Find next.
.IP "\fBN\fP"
Find previous.
.
.IP "\fBF1\fP"
Show simple help.
.IP "\fBF2\fP"
Save current file.
.IP "\fBShift+F2\fP"
Show file with the new name (save as).
.IP "\fBF3\fP"
Goto.
.IP "\fBF5\fP"
Find.
.IP "\fBShift+F5\fP"
Find next.
.IP "\fBF6\fP"
Fill the range with a pattern.
.IP "\fBF7\fP"
Insert bytes into the file.
.IP "\fBF8\fP"
Cut out bytes from the file.
.IP "\fBF9\fP"
Viewer setup.
.IP "\fBEsc\fP, \fBF10\fP"
Exit the program.
.
.SH NOTES
For suggestions, comments, bug reports etc. visit https://github.com/artemsen/xvi
.SH AUTHOR
Artem Senichev <artemsen@gmail.com>
.
