.\" XVI hexadecimal editor
.\" Copyright (C) 2021 Artem Senichev <artemsen@gmail.com>
.TH XVI 1 2021-11-21 xvi "XVI editor manual"
.SH NAME
xvi \- hexadecimal editor
.SH SYNOPSIS
xvi [\fIOPTIONS\fR...] \fIFILE...\fR
.SH DESCRIPTION
\fBxvi\fR is the hex editor with ncurses based user interface.
.SH OPTIONS
.IP "\fB\-h\fR, \fB\-\-help\fR"
Display help message.
.IP "\fB\-v\fR, \fB\-\-version\fR"
Display version information.
.IP "\fB\-o\fR, \fB\-\-offset\fR \fIADDRESS\fR"
Set the initial position of the cursor.
.\" keys
.SH KEYBINDINGS
.SS Common
.IP "\fBArrows\fR and vim-like moving keys (\fBh\fR,\fBj\fR,\fBk\fR,\fBl\fR)"
Move cursor.
.IP "\fBShift+Up\fR, \fBShift+Down\fR"
Scroll one line up/down.
.IP "\fBShift+Left\fR, \fBShift+Right\fR"
Jump to the next/previous 4-bytes aligned word.
.IP "\fBAlt+Left\fR, \fBAlt+Up\fR"
Jump to the previous closest changed byte.
.IP "\fBAlt+Right\fR, \fBAlt+Down\fR"
Jump to the next closest changed byte.
.IP "\fBTab\fR, \fBCtrl+Right\fR"
Set focus to the next field (HEX/ASCII).
.IP "\fBShift-Tab\fR, \fBCtrl+Left\fR"
Set focus to the previous field (HEX/ASCII).
.IP "\fBCtrl+Up\fR"
Set focus to the previous document.
.IP "\fBCtrl+Down\fR"
Set focus to the next document.
.IP "\fBShift+Up\fR, \fBShift+Down\fR"
Scroll one line up/down.
.IP "\fBPgUp\fR, \fBPgDown\fR"
Scroll one page up/down.
.IP "\fBHome\fR, \fBEnd\fR"
Move cursor to the start/end of the current line.
.IP "\fBCtrl+Home\fR, \fBCtrl+End\fR"
Move cursor to the start/end of the current file.
.IP "\fBCtrl+z\fR"
Undo last change.
.IP "\fBCtrl+r\fR, \fBCtrl+y\fR"
Redo last change.
.SS HEX field focused
.IP "\fBu\fR"
Undo last change.
.IP "\fBg\fR, \fBG\fR"
Move cursor to the start/end of the current file.
.IP "\fB:\fP"
Goto (jump to offset).
.IP "\fB/\fP"
Find sequence.
.IP "\fBn\fP"
Find next entry.
.IP "\fBN\fP"
Find previous entry.
.IP "\fBF1\fP"
Show mini help.
.IP "\fBF2\fP"
Save the current file.
.IP "\fBShift+F2\fP"
Save the current file with a new name (save as).
.IP "\fBF3\fP"
Goto (jump to offset).
.IP "\fBF5\fP"
Find sequence.
.IP "\fBShift+F5\fP"
Find next entry.
.IP "\fBF6\fP"
Fill the range with a pattern.
.IP "\fBF7\fP"
Insert bytes into the file.
.IP "\fBF8\fP"
Cut out bytes from the file.
.IP "\fBF9\fP"
Viewer setup.
.IP "\fBEsc\fP, \fBF10\fP"
Exit the program.
.\" related man pages
.SH SEE ALSO
xvirc(5)
.\" link to homepage
.SH BUGS
For suggestions, comments, bug reports etc. visit the
.UR https://github.com/artemsen/xvi
project homepage
.UE .
